name:                adventofcode2021
version:             0.1.0.0
github:              "groscoe/haskell-advent-of-code-2021"
license:             MIT
author:              "Gustavo Roscoe"
maintainer:          "gustavo@gustavoroscoe.com"
copyright:           "2021 Gustavo Roscoe"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/groscoe/haskell-advent-of-code-2021#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  adventofcode2021-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    dependencies:
    - adventofcode2021

tests:
  adventofcode2021-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -rtsopts
    dependencies:
    - adventofcode2021

benchmarks:
  adventofcode2021-bench:
    main: Main.hs
    source-dirs: benchmark
    ghc-options:
      - -O2
    dependencies:
      - criterion
      - adventofcode2021